server:
  port: 8000
  servlet:
    context-path: /app
spring:
  application:
    name: app
  redis:
    port: 6379
    host: 127.0.0.1
  datasource:
    platform: mysql
    sql-script-encoding: utf-8
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aop
    username: root
    password: 123456